import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@mf1/styles/Home.module.css'
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ['latin'] })
const Remote = dynamic(() => import('next2/remote'));
const React1_Timer = dynamic(
    () => import('react1/Timer'), {
        ssr: false
    }
);
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Remote/>
        <React1_Timer />
    </>
  )
}
